//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightHomeTask.DbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightsDbEntities : DbContext
    {
        public FlightsDbEntities()
            : base("name=FlightsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airplaneess> Airplaneesses { get; set; }
        public virtual DbSet<Citieess> Citieesses { get; set; }
        public virtual DbSet<FlightType> FlightTypes { get; set; }
        public virtual DbSet<Pilottt> Pilottts { get; set; }
        public virtual DbSet<SScheduleess> SScheduleesses { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
    }
}
